### ISSUE TITLE
Goals Unattainble

### ISSUE THREAD

**Issue by coryetzkorn** [melanierichards/goals#1]
Goals cannot be achieved when inputs are disabled.
Please fix as ASAP as possible.

Incorrect
`
<input type="checkbox" class="task-list-item-checkbox" disabled="disabled">
`

Correct
`
<input type="checkbox" class="task-list-item-checkbox">
`

**Comment by melanierichards** [comment]
Cute title :P I think the GH markdown outputs disabled checkboxes here so you're forced to commit those changes. #bydesign
